language: php
php:
  - 5.4
  - 5.5
  - 5.6
script:
  - composer install
  - phpunit -c tests/unit/ --coverage-clover build/logs/clover.xml
after_success:
  - composer require codeclimate/php-test-reporter
  - CODECLIMATE_REPO_TOKEN=6cde41e957e7c38ff18bd750dcb9f8d72bd6bcdeeb9da466174fbb4c359e92d1 vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
  - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
  - php phpcs.phar -n --standard=PSR1,PSR2 src/