language: php
php:
  - 5.5
  - 5.6
script:
  - composer install
  - phpunit -c tests/unit/ --coverage-clover build/logs/clover.xml
after_script:
  - CODECLIMATE_REPO_TOKEN=6f17b5bcf96575d5cea99a6af56520bab37591653a9c8955dd602a43f5276fc4 ./vendor/bin/test-reporter 
