language: php
php:
  - 5.5
  - 5.6
script:
  - composer install
  - composer require codeclimate/php-test-reporter --dev
  - phpunit -c tests/unit/ --coverage-clover build/logs/clover.xml
after_script:
after_script:
  - CODECLIMATE_REPO_TOKEN="..." vendor/bin/test-reporter --stdout > codeclimate.json
  - curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reportsaddons:
    code_climate:
        repo_token: 6f17b5bcf96575d5cea99a6af56520bab37591653a9c8955dd602a43f5276fc4
